version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    environment:
      REDIS_PASSWORD: redis
      REDIS_USER: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/data
